<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.41">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2025-02-05">

<title>CAD Time Stamp Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="test2_files/libs/clipboard/clipboard.min.js"></script>
<script src="test2_files/libs/quarto-html/quarto.js"></script>
<script src="test2_files/libs/quarto-html/popper.min.js"></script>
<script src="test2_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="test2_files/libs/quarto-html/anchor.min.js"></script>
<link href="test2_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="test2_files/libs/quarto-html/quarto-syntax-highlighting-48ffa3e5b9d089919c6712c39e5b00f2.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="test2_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="test2_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="test2_files/libs/bootstrap/bootstrap-1bc8a17f135ab3d594c857e9f48e611b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="test2_files/libs/kePrint-0.0.1/kePrint.js"></script>

<link href="test2_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">



</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Contents</h2>
   
  <ul>
  <li><a href="#cad-time-stamp-analysis" id="toc-cad-time-stamp-analysis" class="nav-link active" data-scroll-target="#cad-time-stamp-analysis"><span class="header-section-number">1</span> CAD Time Stamp Analysis</a>
  <ul class="collapse">
  <li><a href="#authors-note" id="toc-authors-note" class="nav-link" data-scroll-target="#authors-note"><span class="header-section-number">1.1</span> Author’s Note</a></li>
  <li><a href="#data-cleaning-and-preparation" id="toc-data-cleaning-and-preparation" class="nav-link" data-scroll-target="#data-cleaning-and-preparation"><span class="header-section-number">1.2</span> Data Cleaning and Preparation</a>
  <ul class="collapse">
  <li><a href="#column-definitions" id="toc-column-definitions" class="nav-link" data-scroll-target="#column-definitions"><span class="header-section-number">1.2.1</span> Column Definitions</a></li>
  </ul></li>
  <li><a href="#data-analysis" id="toc-data-analysis" class="nav-link" data-scroll-target="#data-analysis"><span class="header-section-number">1.3</span> Data Analysis</a>
  <ul class="collapse">
  <li><a href="#missing-data" id="toc-missing-data" class="nav-link" data-scroll-target="#missing-data"><span class="header-section-number">1.3.1</span> Missing Data</a></li>
  <li><a href="#initial-observations" id="toc-initial-observations" class="nav-link" data-scroll-target="#initial-observations"><span class="header-section-number">1.3.2</span> Initial Observations</a></li>
  <li><a href="#eda" id="toc-eda" class="nav-link" data-scroll-target="#eda"><span class="header-section-number">1.3.3</span> EDA</a></li>
  <li><a href="#first-visuals" id="toc-first-visuals" class="nav-link" data-scroll-target="#first-visuals"><span class="header-section-number">1.3.4</span> First Visuals</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">CAD Time Stamp Analysis</h1>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">February 5, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="cad-time-stamp-analysis" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> CAD Time Stamp Analysis</h1>
<p>The following analysis is desinged to look at the time stamps related to service calls for the past 13 months and determine the significance of event sequencing and investigate the challenges presented when calls for service are manipulated after the first call closure.</p>
<section id="authors-note" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="authors-note"><span class="header-section-number">1.1</span> Author’s Note</h2>
<p>The data was harvested from the CentralSquare Enterprise CAD Reporting Database. The two database tables that were queried are Response_Master_Incident and Response_Master_Incident_Ext. These two tables contain all of the time stamps needed for the analysis. For this analysis, the data consists of call information, including the method of call reception, priority number, and the problem type from 01 January 2024 through 31 January 2025. This dataset consists of 178780 rows prior to any cleaning of adjustments.</p>
</section>
<section id="data-cleaning-and-preparation" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="data-cleaning-and-preparation"><span class="header-section-number">1.2</span> Data Cleaning and Preparation</h2>
<p>To ensure the data will be useful to us, the first step is cleaning. In this instance, after extracting the data from the archive database, cleaning was done in the Excel file, including removing the “NULL” values and replacing them with empty cells. This forces R to insert its own NULL value and allows it to correctly assign the data types to the columns. Here is a view of that so you can see what we have.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>tibble [178,780 × 50] (S3: tbl_df/tbl/data.frame)
 $ ID               : num [1:178780] 2659640 2659641 2659642 2659643 2659644 ...
 $ Reception        : chr [1:178780] "E-911" "E-911" "E-911" "E-911" ...
 $ Problem          : chr [1:178780] "911 TRANSFER VSP" "BLS EMERGENCY" NA NA ...
 $ Priority         : num [1:178780] 7 3 NA NA 2 NA 2 1 NA NA ...
 $ Agency           : chr [1:178780] "LAW" "FIRE" "DEC" "DEC" ...
 $ Jurisdiction     : chr [1:178780] "Alexandria PD" "200 ALX" "DEC" "DEC" ...
 $ Response_Date    : POSIXct[1:178780], format: "2024-01-01 00:01:09" "2024-01-01 00:02:05" ...
 $ Clock_Start      : POSIXct[1:178780], format: "2024-01-01 00:01:09" "2024-01-01 00:02:05" ...
 $ Phone_Start      : POSIXct[1:178780], format: "2024-01-01 00:01:08" "2024-01-01 00:02:04" ...
 $ Fixed_Phone_Start: POSIXct[1:178780], format: "2024-01-01 00:01:08" "2024-01-01 00:02:04" ...
 $ First_Keystroke  : POSIXct[1:178780], format: "2024-01-01 00:01:09" "2024-01-01 00:02:05" ...
 $ DELTA_RD_CST     : num [1:178780] 0 0 0 0 0 0 22 0 0 0 ...
 $ DELTA_RD_TPU     : num [1:178780] -1 -1 0 0 0 0 0 -2 0 0 ...
 $ DELTA_RD_FTPU    : num [1:178780] -1 -1 0 0 0 0 NA -2 0 0 ...
 $ DELTA_RD_FCTK    : num [1:178780] 0 0 0 0 4 0 0 9 0 0 ...
 $ DELTA_CST_TPU    : num [1:178780] -1 -1 0 0 0 0 -22 -2 0 0 ...
 $ DELTA_CST_FTPU   : num [1:178780] -1 -1 0 0 0 0 NA -2 0 0 ...
 $ DELTA_CST_FCTK   : num [1:178780] 0 0 0 0 4 0 -22 9 0 0 ...
 $ DELTA_TPU_FTPU   : num [1:178780] 0 0 0 0 0 0 NA 0 0 0 ...
 $ DELTA_TPU_FCTK   : num [1:178780] 1 1 0 0 4 0 0 11 0 0 ...
 $ DELTA_FTPU_FCTK  : num [1:178780] 1 1 0 0 4 0 NA 11 0 0 ...
 $ Viewed           : POSIXct[1:178780], format: NA "2024-01-01 00:04:33" ...
 $ Queued           : POSIXct[1:178780], format: "2024-01-01 00:01:44" "2024-01-01 00:03:11" ...
 $ Fixed_Queued     : POSIXct[1:178780], format: "2024-01-01 00:01:44" "2024-01-01 00:03:11" ...
 $ DELTA_QUEUES     : num [1:178780] 0 0 0 0 0 0 0 0 0 0 ...
 $ Phone_End        : POSIXct[1:178780], format: "2024-01-01 00:01:45" "2024-01-01 00:08:57" ...
 $ Fixed_Phone_End  : POSIXct[1:178780], format: "2024-01-01 00:01:45" "2024-01-01 00:08:57" ...
 $ DELTA_CALLTAKING : num [1:178780] 0 0 0 0 0 0 0 0 0 0 ...
 $ First_Dispatch   : POSIXct[1:178780], format: NA "2024-01-01 00:03:15" ...
 $ First_Ack        : POSIXct[1:178780], format: NA "2024-01-01 00:05:13" ...
 $ First_Enroute    : POSIXct[1:178780], format: NA "2024-01-01 00:05:13" ...
 $ First_Arrived    : POSIXct[1:178780], format: NA "2024-01-01 00:10:32" ...
 $ First_Clear      : POSIXct[1:178780], format: NA "2024-01-01 01:40:47" ...
 $ Call_Closed      : POSIXct[1:178780], format: "2024-01-01 00:01:45" "2024-01-01 01:40:48" ...
 $ Fixed_Call_Closed: POSIXct[1:178780], format: "2024-01-01 00:01:45" "2024-01-01 01:40:48" ...
 $ STEP_1           : num [1:178780] -1 -1 0 0 0 0 -22 -2 0 0 ...
 $ STEP_2           : num [1:178780] 1 1 0 0 4 0 0 11 0 0 ...
 $ STEP_2A          : num [1:178780] NA 148 NA NA 19 NA 22 57 NA NA ...
 $ STEP_2B          : num [1:178780] NA -82 NA NA -2 NA -22 -9 NA NA ...
 $ STEP_3           : num [1:178780] 35 66 37 25 17 197 0 48 19 101 ...
 $ CALL_TIME        : num [1:178780] 37 413 37 25 175 197 0 350 19 102 ...
 $ STEP_4           : num [1:178780] NA 4 NA NA 21 NA 3 24 NA NA ...
 $ STEP_5           : num [1:178780] NA 118 NA NA 2 NA 94 18 NA NA ...
 $ STEP_6           : num [1:178780] NA 0 NA NA 0 NA 0 0 NA NA ...
 $ STEP_7           : num [1:178780] NA 319 NA NA 193 NA 272 224 NA NA ...
 $ STEP_8           : num [1:178780] NA 5415 NA NA 3210 ...
 $ STEP_9           : num [1:178780] NA 0 NA NA 20928 ...
 $ STEP_10          : num [1:178780] NA 5415 NA NA 24138 ...
 $ TOTAL_TIME_A     : num [1:178780] 36 5922 37 26 24375 ...
 $ TOTAL_TIME_B     : num [1:178780] 36 5922 37 26 24375 ...</code></pre>
</div>
</div>
<p>This leaves us well positioned because we now have the character (chr) columns, numeric (num) columns, and time stamps (POSIXct) defined. The numeric columns will be expressed as BIGINT in the background which is what we want for now.</p>
<section id="column-definitions" class="level3" data-number="1.2.1">
<h3 data-number="1.2.1" class="anchored" data-anchor-id="column-definitions"><span class="header-section-number">1.2.1</span> Column Definitions</h3>
<p>The columns for this dataset are defined as follows:</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>Note that any negative values in the deltas occur when the time for the rightmost variable is earlier than the time recorded for the leftmost variable.</p>
</div>
</div>
<div>
<ol type="1">
<li>ID: <em>This is the ID column from the CAD. We will use it to isolate specific calls for further analyses.</em></li>
<li>Reception: <em>This is how the call entered DECC. <strong>‘Null’</strong> Values will be changed to ‘Not Recorded’ for analytical purposes.</em></li>
<li>Problem: <em>This is the final problem nature as updated by the parties working the call</em></li>
<li>Priority: <em>This is the relative importance level assigned by DECC. This will be used for further analyses</em></li>
<li>Agency: <em>This indicates if the call was for LAW, FIRE, or DEC.</em></li>
<li>Jurisdiction: <em>This indicates for whom the call was run.</em></li>
<li>Response_Date: <em>This, per CS, is the timestamp indicating when the ID was created and is frequently used, by them, as the <strong>start</strong> of the call.</em></li>
<li>Clock_Start: <em>This should be, per CS, the <strong>actual</strong> starting point for the call.</em></li>
<li>Phone_Start: <em>This timestamp identifies when the CAD acknowledged the start of the phone call for the event.</em></li>
<li>Fixed_Phone_Start: <em>This timestamp also identifies when the CAD acknowledged the start of the phone call for the event, but is deemed <strong>immutable</strong> by the software.</em></li>
<li>First_Keystroke: <em>This timestamp identifies when the CAD software registers the first keystroke related to the event</em></li>
<li>DELTA_RD_CST: <em>This is the difference, hence Δ, between the Response_Date and ClockStartTime columns.</em></li>
<li>DELTA_RD_TPU: <em>This is the difference between the Response_Date and the Time_PhonePickUp columns.</em></li>
<li>DELTA_RD_FTPU: <em>This is the difference between the Response_Date and the Fixed_Time_PhonePickUp columns.</em></li>
<li>DELTA_RD_FCTK: <em>This is the difference between the Response_Date and the Time_FirstCallTakingKeystroke columns.</em></li>
<li>DELTA_CST_TPU: <em>This is the difference between the ClockStartTime and the Time_PhonePickUp columns.</em></li>
<li>DELTA_CST_FTPU: <em>This is the difference between the ClockStartTime and the Fixed_Time_PhonePickUp columns.</em></li>
<li>DELTA CST_FCTK: <em>This is the difference between the ClockStartTime and the Time_FirstCallTakingKeystroke columns.</em></li>
<li>DELTA_TPU_FTPU: <em>This is the difference between the Time_PhonePickUp and Fixed_Time_PhonePickUp columns.</em></li>
<li>DELTA_TPU_FCTK: <em>This is the difference between the Time_PhonePickUp and Time_FirstCallTakingKeystroke columns.</em></li>
<li>DELTA_FTPU_FCTK: <em>This is the difference between the Fixed_Time_PhonePickUp and Time_FirstCallTakingKeystroke columns.</em></li>
<li>Viewed: <em>This is defined by the vendor as the time the call was first viewed in the Call Taking Form.</em></li>
<li>Queued: <em>This is the time when the call has been released to be dispatched by the calltaker.</em></li>
<li>Fixed_Queued: <em>This is the <strong>fixed</strong> time when the call has been released to be dispatched by the calltaker.</em></li>
<li>DELTA_QUEUES: <em>This is the difference between the Time_CallEnteredQueue and Fixed_Time_CallEnteredQueue columns.</em></li>
<li>Phone_End: <em>This is the time when the caller is released.</em></li>
<li>Fixed_Phone_End: <em>This is the <strong>fixed</strong> time when the caller is released.</em></li>
<li>DELTA_CALLTAKING: <em>This is the difference between the Time_CallTakingComplete and Fixed_Time_CallTakingComplete columns.</em></li>
<li>First_Dispatched: <em>This is the time when the dispatcher assigned the first unit to the call.</em></li>
<li>First_Ack: <em>This is the time when the first unit acknowledges receiving the dispatched call.</em></li>
<li>First_Enroute: <em>This is the time the first dispatched unit marks or is marked ‘En Route’ for the assigned call.</em></li>
<li>First_Arrived: <em>This is the time the first dispatched unit marks or is marked ‘Arrived’ for the assigned call.</em></li>
<li>First_Clear: <em>This is the time that the first unit clears or leaves the call after arrival.</em></li>
<li>Call_Closed: <em>This is the time that the final unit is cleared from the call, closing the event out.</em></li>
<li>Fixed_Call_Closed: <em>This is the <strong>fixed</strong> time that the final unit is cleared from the call, closing the event out.</em></li>
<li>STEP_1: <em>This is the time difference between the ClockStartTime and the Time_PhonePickUp columns.</em></li>
<li>STEP_2: <em>This is the time difference between the Time_PhonePickUp and the Time_FirstCallTakingKeystroke columns.</em></li>
<li>STEP_2A: <em>This is the time difference between the Time_PhonePickUp and TimeCallViewed columns.</em></li>
<li>STEP_2B: <em>This is the time difference between the TimeCallViewed and Time_FirstCallTakingKeystroke columns.</em></li>
<li>STEP_3: <em>This is the time difference between the Time_FirstCallTakingKeystroke and Time_CallEnteredQueue columns.</em></li>
<li>CALL_TIME: <em>This is the time difference between the Time_PhonePickUp and Time_CallTakingComplete columns.</em></li>
<li>STEP_4: <em>This is the time difference between the Time_CallEnteredQueue and Time_First_Unit_Assigned columns.</em></li>
<li>STEP_5: <em>This is the time difference between the Time_First_Unit_Assigned and TimeFirstUnitDispatchAcknowledged columns.</em></li>
<li>STEP_6: <em>This is the time difference between the TimeFirstUnitDispatchAcknowledged and Time_First_Unit_Enroute columns.</em></li>
<li>STEP_7: <em>This is the time difference between the Time_First_Unit_Enroute and Time_First_Unit_Arrived columns.</em></li>
<li>STEP_8: <em>This is the time difference between the Time_First_Unit_Arrived and TimeFirstCallCleared columns.</em></li>
<li>STEP_9: <em>This is the time difference between the TimeFirstCallCleared and Time_CallClosed columns.</em></li>
<li>STEP_10: <em>This is the time difference between the Time_First_Unit_Arrived and Time_CallClosed columns.</em></li>
<li>TOTAL_TIME_A: <em>This is the time difference between the Response_Date and Time_CallClosed columns.</em></li>
<li>TOTAL_TIME_B: <em>This is the time difference between the ClockStartTime and Time_CallClosed columns.</em></li>
</ol>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Please note that there should not be, if calls are not re-opened, any delta between a time stamp and its ‘Fixed’ counterpart.</p>
</div>
</div>
<p>In the list above, the Steps columns are meant to follow a call from the time the clock starts to the time the clock stops. I’ve identified a possible 10 step timing chain that would allow us to step through the history of a call. There are multiple possible steps for the second step depending on management preferences. Once we have established the chain time wise, then we can use these steps as a tool to investigate specific events and to get better analyses and insights from processes overall. This can also assist in trend analyses. Where there are no entries for some of these time points, we may need to create alternative elapsed time points to create our steps. Those decisions are part of this project’s goals.</p>
<p>You will note there are some columns duplicated because they are meant to be used for different analyses using the same dataset. Traditionally, we shouldn’t have to do this, but I chose to make this distinction for ease of use.</p>
</section>
</section>
<section id="data-analysis" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="data-analysis"><span class="header-section-number">1.3</span> Data Analysis</h2>
<section id="missing-data" class="level3" data-number="1.3.1">
<h3 data-number="1.3.1" class="anchored" data-anchor-id="missing-data"><span class="header-section-number">1.3.1</span> Missing Data</h3>
<p>Looking at the dataset, here is a graph of missing data:</p>
<div class="cell" data-warn_large_data="false">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="test2_files/figure-html/missing_data-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The graph shows that we have over 70,000 calls where we never recorded an arrival to the event. We might need to add a disposition for the calls to see if there is a correlation between missing values and disposition codes. I’ve included a printout of the number of missing rows by column to assist in the numbers.</p>
<div class="cell" data-warn_large_data="false">
<div class="cell-output cell-output-stdout">
<pre><code>               ID         Reception           Problem          Priority 
                0             28779             23858             23861 
           Agency      Jurisdiction     Response_Date       Clock_Start 
                0                77                 0              8241 
      Phone_Start Fixed_Phone_Start   First_Keystroke      DELTA_RD_CST 
             6450              6516              6450              8241 
     DELTA_RD_TPU     DELTA_RD_FTPU     DELTA_RD_FCTK     DELTA_CST_TPU 
             6450              6516              6450             10168 
   DELTA_CST_FTPU    DELTA_CST_FCTK    DELTA_TPU_FTPU    DELTA_TPU_FCTK 
            10234             10168              6516              6450 
  DELTA_FTPU_FCTK            Viewed            Queued      Fixed_Queued 
             6516             73125                 0                 0 
     DELTA_QUEUES         Phone_End   Fixed_Phone_End  DELTA_CALLTAKING 
                0              6450              6450              6450 
   First_Dispatch         First_Ack     First_Enroute     First_Arrived 
            62044             70820             64274             73291 
      First_Clear       Call_Closed Fixed_Call_Closed            STEP_1 
            67202                95                82             10168 
           STEP_2           STEP_2A           STEP_2B            STEP_3 
             6450             75013             73125              6450 
        CALL_TIME            STEP_4            STEP_5            STEP_6 
             6450             62044             70821             70823 
           STEP_7            STEP_8            STEP_9           STEP_10 
            73291             76129             67204             73292 
     TOTAL_TIME_A      TOTAL_TIME_B 
               95              8334 </code></pre>
</div>
</div>
<p>With this information, we will need to address some of the NULL values in order to determine if there are any correlations. Immediately, you can see that the steps where the arrival time is missing also have missing values.</p>
<p>We can repeat the graph to ensure that there are no longer any missing values for these four columns.</p>
<div class="cell" data-warn_large_data="false">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="test2_files/figure-html/missing_data2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Now that we have those addressed, let’s look at how many negative values we have across the thirteen month period. For this, I’m going to create a variable for each of the numeric columns, except Priority, and calculate a percentage of the data we do have that is negative and missing. That table can be found below:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Column</th>
<th style="text-align: center;">Negative Rows</th>
<th style="text-align: center;">NA Rows</th>
<th style="text-align: center;">Neg Percentage</th>
<th style="text-align: center;">NA Percentage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">DELTA_RD_CST</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">8241</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">4.61</td>
</tr>
<tr class="even">
<td style="text-align: center;">DELTA_RD_TPU</td>
<td style="text-align: center;">86934</td>
<td style="text-align: center;">6450</td>
<td style="text-align: center;">50.45</td>
<td style="text-align: center;">3.61</td>
</tr>
<tr class="odd">
<td style="text-align: center;">DELTA_RD_FTPU</td>
<td style="text-align: center;">86934</td>
<td style="text-align: center;">6516</td>
<td style="text-align: center;">50.47</td>
<td style="text-align: center;">3.64</td>
</tr>
<tr class="even">
<td style="text-align: center;">DELTA_RD_FCTK</td>
<td style="text-align: center;">6959</td>
<td style="text-align: center;">6450</td>
<td style="text-align: center;">4.04</td>
<td style="text-align: center;">3.61</td>
</tr>
<tr class="odd">
<td style="text-align: center;">DELTA_CST_TPU</td>
<td style="text-align: center;">99001</td>
<td style="text-align: center;">10168</td>
<td style="text-align: center;">58.72</td>
<td style="text-align: center;">5.69</td>
</tr>
<tr class="even">
<td style="text-align: center;">DELTA_CST_FTPU</td>
<td style="text-align: center;">98935</td>
<td style="text-align: center;">10234</td>
<td style="text-align: center;">58.7</td>
<td style="text-align: center;">5.72</td>
</tr>
<tr class="odd">
<td style="text-align: center;">DELTA_CST_FCTK</td>
<td style="text-align: center;">19026</td>
<td style="text-align: center;">10168</td>
<td style="text-align: center;">11.28</td>
<td style="text-align: center;">5.69</td>
</tr>
<tr class="even">
<td style="text-align: center;">DELTA_TPU_FTPU</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">6516</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">3.64</td>
</tr>
<tr class="odd">
<td style="text-align: center;">DELTA_TPU_FCTK</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">6450</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">3.61</td>
</tr>
<tr class="even">
<td style="text-align: center;">DELTA_FTPU_FCTK</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">6516</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">3.64</td>
</tr>
<tr class="odd">
<td style="text-align: center;">DELTA_QUEUES</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td style="text-align: center;">DELTA_CALLTAKING</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">6450</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">3.61</td>
</tr>
<tr class="odd">
<td style="text-align: center;">STEP_1</td>
<td style="text-align: center;">99001</td>
<td style="text-align: center;">10168</td>
<td style="text-align: center;">58.72</td>
<td style="text-align: center;">5.69</td>
</tr>
<tr class="even">
<td style="text-align: center;">STEP_2</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">6450</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">3.61</td>
</tr>
<tr class="odd">
<td style="text-align: center;">STEP_2A</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">75013</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">41.96</td>
</tr>
<tr class="even">
<td style="text-align: center;">STEP_2B</td>
<td style="text-align: center;">105565</td>
<td style="text-align: center;">73125</td>
<td style="text-align: center;">99.91</td>
<td style="text-align: center;">40.9</td>
</tr>
<tr class="odd">
<td style="text-align: center;">STEP_3</td>
<td style="text-align: center;">582</td>
<td style="text-align: center;">6450</td>
<td style="text-align: center;">0.34</td>
<td style="text-align: center;">3.61</td>
</tr>
<tr class="even">
<td style="text-align: center;">CALL_TIME</td>
<td style="text-align: center;">586</td>
<td style="text-align: center;">6450</td>
<td style="text-align: center;">0.34</td>
<td style="text-align: center;">3.61</td>
</tr>
<tr class="odd">
<td style="text-align: center;">STEP_4</td>
<td style="text-align: center;">2369</td>
<td style="text-align: center;">62044</td>
<td style="text-align: center;">2.03</td>
<td style="text-align: center;">34.7</td>
</tr>
<tr class="even">
<td style="text-align: center;">STEP_5</td>
<td style="text-align: center;">67</td>
<td style="text-align: center;">70821</td>
<td style="text-align: center;">0.06</td>
<td style="text-align: center;">39.61</td>
</tr>
<tr class="odd">
<td style="text-align: center;">STEP_6</td>
<td style="text-align: center;">5578</td>
<td style="text-align: center;">70823</td>
<td style="text-align: center;">5.17</td>
<td style="text-align: center;">39.61</td>
</tr>
<tr class="even">
<td style="text-align: center;">STEP_7</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">73291</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">41</td>
</tr>
<tr class="odd">
<td style="text-align: center;">STEP_8</td>
<td style="text-align: center;">9591</td>
<td style="text-align: center;">76129</td>
<td style="text-align: center;">9.34</td>
<td style="text-align: center;">42.58</td>
</tr>
<tr class="even">
<td style="text-align: center;">STEP_9</td>
<td style="text-align: center;">11</td>
<td style="text-align: center;">67204</td>
<td style="text-align: center;">0.01</td>
<td style="text-align: center;">37.59</td>
</tr>
<tr class="odd">
<td style="text-align: center;">STEP_10</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">73292</td>
<td style="text-align: center;">0.01</td>
<td style="text-align: center;">41</td>
</tr>
<tr class="even">
<td style="text-align: center;">TOTAL_TIME_A</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">95</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0.05</td>
</tr>
<tr class="odd">
<td style="text-align: center;">TOTAL_TIME_B</td>
<td style="text-align: center;">113</td>
<td style="text-align: center;">8334</td>
<td style="text-align: center;">0.07</td>
<td style="text-align: center;">4.66</td>
</tr>
</tbody>
</table>
<p>Because of the way the programming language processes our requests, I’m going to reverse the fields in a few of the areas where I have no negative time-to-event values to ensure that both directions are equal in value counts.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Column</th>
<th style="text-align: center;">Negative Rows</th>
<th style="text-align: center;">NA Rows</th>
<th style="text-align: center;">Neg Percentage</th>
<th style="text-align: center;">NA Percentage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">DELTA_TPU_FTPU2</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">6516</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">3.64</td>
</tr>
<tr class="even">
<td style="text-align: center;">DELTA_TPU_FCTK2</td>
<td style="text-align: center;">93554</td>
<td style="text-align: center;">6450</td>
<td style="text-align: center;">54.29</td>
<td style="text-align: center;">3.61</td>
</tr>
<tr class="odd">
<td style="text-align: center;">DELTA_FTPU_FCTK2</td>
<td style="text-align: center;">93554</td>
<td style="text-align: center;">6516</td>
<td style="text-align: center;">54.31</td>
<td style="text-align: center;">3.64</td>
</tr>
<tr class="even">
<td style="text-align: center;">DELTA_QUEUES2</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="odd">
<td style="text-align: center;">DELTA_CALLTAKING2</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">6450</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">3.61</td>
</tr>
</tbody>
</table>
</section>
<section id="initial-observations" class="level3" data-number="1.3.2">
<h3 data-number="1.3.2" class="anchored" data-anchor-id="initial-observations"><span class="header-section-number">1.3.2</span> Initial Observations</h3>
<p>Initially, it should be noted that there are a lot of negative time-to-event values between the Response_Date and both of the timestamps for when the phone is picked up. This could imply that the Response_Date column is also being impacted, at times, when the call is reopened. If this is the case, then I would recommend using that column for fencing entries and, even then, with caution. You can also see a lot of negative values between the ClockStartTime and the phone pickups. Again, this implies, to me, that this column may not be the most accurate. From appearances, I would recommend future analyses start with the Fixed_Time_PhonePickup as the initial point and disregard the call start time.</p>
<p>I am pleased to see that there are no negative time-to-event values between the Time_PhonePickUp and Fixed_Time_PhonePickUp columns. That implies that there are no issues with reopening calls there. I would recommend using the <em>Fixed</em> value whenever possible. Those are implied to be immutable per CentralSquare. I am also pleased to see that see there are no negative time-to-event values for the span between the phone pickup and the first calltaking keystroke. The only drawback I saw is in the number of rows missing for both the Time_PhonePickUp and Fixed_Time_PhonePickUp columns. There are 6450 and 6516 missing rows respectively. These represent 3.61 percent and 3.64 percent of the columns missing respectively. The good news is that, at under 5% of the dataset, initial EDA and other preliminary work can safely discard those columns.</p>
<p>We should abandon the TimeCallViewed column. There are too many missing values. Attempting to use this column in time-to-event analyses resulted in over 40% of those events having missing data. While abandoned calls may be considered censored in survival analyses, applying censoring rules to these columns renders that column inert analytically. Therefore abandoning the column is the only analytical course of action.</p>
<p>Another positive observation was a lack of negative values between the time stamps for calls entering the dispatch queue. Additionally, there were no missing values between the two columns either. So we appear to be able to use either column, again I recommend defaulting to the <em>Fixed</em> alternative for analytical purposes.</p>
<p>The reversals show that where there were no negative time-to-event values between the phone pickup timestamps, the first entering queue timestamps, the completion of the call taking process timestamps. This is heartening and allows us to select either of the two timestamps for the same event. The interesting thing to note is that there is a delta in about 50% of cases between the phone pickup and the first call taking keystroke. This confirms the idea that we can build a call flow process for survival analyses that starts with the phone pickup and continues with the first keystroke. It also shows that nearly half of the time, the timestamps for phone pickup and first keystroke are identical.</p>
</section>
<section id="eda" class="level3" data-number="1.3.3">
<h3 data-number="1.3.3" class="anchored" data-anchor-id="eda"><span class="header-section-number">1.3.3</span> EDA</h3>
<p>Now that we know what we’re facing with respect to negative values and missing values, the first stage of analysis can take place. This first summary will leave the negative values in place, but will remove the missing values from the calculation.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small" data-quarto-postprocess="true">
<caption>Weekly Elapsed Time Summary Table</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Minimum</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Mean</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Median</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Q1.25%</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Q3.75%</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Maximum</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Std_Dev</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Skewness</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Kurtosis</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">DELTA_RD_CST</td>
<td style="text-align: right;">-571677</td>
<td style="text-align: right;">351.89</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">10663719</td>
<td style="text-align: right;">35765.40</td>
<td style="text-align: right;">200.32</td>
<td style="text-align: right;">51040.83</td>
</tr>
<tr class="even">
<td style="text-align: left;">DELTA_RD_TPU</td>
<td style="text-align: right;">-16</td>
<td style="text-align: right;">-0.80</td>
<td style="text-align: right;">-1</td>
<td style="text-align: right;">-2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.90</td>
<td style="text-align: right;">-0.65</td>
<td style="text-align: right;">0.25</td>
</tr>
<tr class="odd">
<td style="text-align: left;">DELTA_RD_FTPU</td>
<td style="text-align: right;">-16</td>
<td style="text-align: right;">-0.80</td>
<td style="text-align: right;">-1</td>
<td style="text-align: right;">-2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.90</td>
<td style="text-align: right;">-0.65</td>
<td style="text-align: right;">0.25</td>
</tr>
<tr class="even">
<td style="text-align: left;">DELTA_RD_FCTK</td>
<td style="text-align: right;">-10</td>
<td style="text-align: right;">3.40</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">5051</td>
<td style="text-align: right;">27.60</td>
<td style="text-align: right;">76.82</td>
<td style="text-align: right;">10171.81</td>
</tr>
<tr class="odd">
<td style="text-align: left;">DELTA_CST_TPU</td>
<td style="text-align: right;">-10663719</td>
<td style="text-align: right;">-283.97</td>
<td style="text-align: right;">-1</td>
<td style="text-align: right;">-2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">571677</td>
<td style="text-align: right;">33772.02</td>
<td style="text-align: right;">-225.36</td>
<td style="text-align: right;">62965.71</td>
</tr>
<tr class="even">
<td style="text-align: left;">DELTA_CST_FTPU</td>
<td style="text-align: right;">-10663719</td>
<td style="text-align: right;">-284.07</td>
<td style="text-align: right;">-1</td>
<td style="text-align: right;">-2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">571677</td>
<td style="text-align: right;">33778.63</td>
<td style="text-align: right;">-225.32</td>
<td style="text-align: right;">62941.06</td>
</tr>
<tr class="odd">
<td style="text-align: left;">DELTA_CST_FCTK</td>
<td style="text-align: right;">-10663719</td>
<td style="text-align: right;">-279.68</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">571677</td>
<td style="text-align: right;">33772.07</td>
<td style="text-align: right;">-225.36</td>
<td style="text-align: right;">62965.47</td>
</tr>
<tr class="even">
<td style="text-align: left;">DELTA_TPU_FTPU</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">NaN</td>
<td style="text-align: right;">NaN</td>
</tr>
<tr class="odd">
<td style="text-align: left;">DELTA_TPU_FCTK</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4.21</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">5053</td>
<td style="text-align: right;">27.65</td>
<td style="text-align: right;">76.42</td>
<td style="text-align: right;">10101.34</td>
</tr>
<tr class="even">
<td style="text-align: left;">DELTA_FTPU_FCTK</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4.21</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">5053</td>
<td style="text-align: right;">27.65</td>
<td style="text-align: right;">76.40</td>
<td style="text-align: right;">10097.63</td>
</tr>
<tr class="odd">
<td style="text-align: left;">DELTA_QUEUES</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">NaN</td>
<td style="text-align: right;">NaN</td>
</tr>
<tr class="even">
<td style="text-align: left;">DELTA_CALLTAKING</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">NaN</td>
<td style="text-align: right;">NaN</td>
</tr>
<tr class="odd">
<td style="text-align: left;">STEP_1</td>
<td style="text-align: right;">-10663719</td>
<td style="text-align: right;">-283.97</td>
<td style="text-align: right;">-1</td>
<td style="text-align: right;">-2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">571677</td>
<td style="text-align: right;">33772.02</td>
<td style="text-align: right;">-225.36</td>
<td style="text-align: right;">62965.71</td>
</tr>
<tr class="even">
<td style="text-align: left;">STEP_2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4.21</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">5053</td>
<td style="text-align: right;">27.65</td>
<td style="text-align: right;">76.42</td>
<td style="text-align: right;">10101.34</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CALL_TIME</td>
<td style="text-align: right;">-2</td>
<td style="text-align: right;">198.97</td>
<td style="text-align: right;">90</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">207</td>
<td style="text-align: right;">90227</td>
<td style="text-align: right;">548.13</td>
<td style="text-align: right;">35.87</td>
<td style="text-align: right;">4423.98</td>
</tr>
<tr class="even">
<td style="text-align: left;">STEP_3</td>
<td style="text-align: right;">-2</td>
<td style="text-align: right;">4293.26</td>
<td style="text-align: right;">42</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">93</td>
<td style="text-align: right;">15730112</td>
<td style="text-align: right;">113571.13</td>
<td style="text-align: right;">66.89</td>
<td style="text-align: right;">6270.95</td>
</tr>
<tr class="odd">
<td style="text-align: left;">STEP_4</td>
<td style="text-align: right;">-14854005</td>
<td style="text-align: right;">-4836.92</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">265</td>
<td style="text-align: right;">71938</td>
<td style="text-align: right;">123966.19</td>
<td style="text-align: right;">-54.16</td>
<td style="text-align: right;">4107.15</td>
</tr>
<tr class="even">
<td style="text-align: left;">STEP_5</td>
<td style="text-align: right;">-1695</td>
<td style="text-align: right;">1035.30</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">48</td>
<td style="text-align: right;">3627979</td>
<td style="text-align: right;">33709.73</td>
<td style="text-align: right;">61.41</td>
<td style="text-align: right;">4687.81</td>
</tr>
<tr class="odd">
<td style="text-align: left;">STEP_6</td>
<td style="text-align: right;">-3627979</td>
<td style="text-align: right;">-75.50</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">10715</td>
<td style="text-align: right;">11196.51</td>
<td style="text-align: right;">-316.02</td>
<td style="text-align: right;">102138.21</td>
</tr>
<tr class="even">
<td style="text-align: left;">STEP_7</td>
<td style="text-align: right;">-3355</td>
<td style="text-align: right;">785.79</td>
<td style="text-align: right;">211</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">411</td>
<td style="text-align: right;">14853997</td>
<td style="text-align: right;">49026.79</td>
<td style="text-align: right;">270.03</td>
<td style="text-align: right;">80255.55</td>
</tr>
<tr class="odd">
<td style="text-align: left;">STEP_8</td>
<td style="text-align: right;">-14847718</td>
<td style="text-align: right;">2396.61</td>
<td style="text-align: right;">795</td>
<td style="text-align: right;">303</td>
<td style="text-align: right;">2292</td>
<td style="text-align: right;">8711058</td>
<td style="text-align: right;">60703.95</td>
<td style="text-align: right;">-115.97</td>
<td style="text-align: right;">39169.52</td>
</tr>
<tr class="even">
<td style="text-align: left;">STEP_9</td>
<td style="text-align: right;">-284</td>
<td style="text-align: right;">6930.77</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1315</td>
<td style="text-align: right;">14883795</td>
<td style="text-align: right;">119785.64</td>
<td style="text-align: right;">56.36</td>
<td style="text-align: right;">4486.34</td>
</tr>
<tr class="odd">
<td style="text-align: left;">STEP_10</td>
<td style="text-align: right;">-2152</td>
<td style="text-align: right;">9048.81</td>
<td style="text-align: right;">1680</td>
<td style="text-align: right;">580</td>
<td style="text-align: right;">4887</td>
<td style="text-align: right;">10249784</td>
<td style="text-align: right;">110800.21</td>
<td style="text-align: right;">52.69</td>
<td style="text-align: right;">3548.09</td>
</tr>
<tr class="even">
<td style="text-align: left;">TOTAL_TIME_A</td>
<td style="text-align: right;">-2300</td>
<td style="text-align: right;">16750.64</td>
<td style="text-align: right;">1254</td>
<td style="text-align: right;">195</td>
<td style="text-align: right;">4510</td>
<td style="text-align: right;">18518472</td>
<td style="text-align: right;">239705.75</td>
<td style="text-align: right;">33.53</td>
<td style="text-align: right;">1470.26</td>
</tr>
<tr class="odd">
<td style="text-align: left;">TOTAL_TIME_B</td>
<td style="text-align: right;">-10663451</td>
<td style="text-align: right;">17046.01</td>
<td style="text-align: right;">1280</td>
<td style="text-align: right;">170</td>
<td style="text-align: right;">4543</td>
<td style="text-align: right;">18518472</td>
<td style="text-align: right;">248013.95</td>
<td style="text-align: right;">31.13</td>
<td style="text-align: right;">1366.78</td>
</tr>
</tbody>
</table>


</div>
</div>
<section id="eda-observations" class="level4" data-number="1.3.3.1">
<h4 data-number="1.3.3.1" class="anchored" data-anchor-id="eda-observations"><span class="header-section-number">1.3.3.1</span> EDA Observations</h4>
<p>The first thing that should stand out is that there are several mean values that have a negative value. In a time-to-event analysis, this disqualifies this dataset. If you notice, the minimum for some values represents the largest difference between the columns. For example, the maximum negative value between the clock start time and the time the phone was picked up is a little over 123 days. This implies that we answered the phone for that call about 4 months before the clock even started on the event. On the other hand, the maximum positive value for that same field implies that we answered a call about 6.6 days after the clock started. Both of these instances are caused by the call being reopened after close. In these cases, the mean value is also negative showing that we, <em>on average</em>, answered the phone about 4 minutes and 45 seconds before the clock started. In fact, even the median value shows that we answered the call a second before the clock started. As discussed above, this suggests that we do not use the ClockStartTime column in the database for future work. Unlike the Response_Date column which can be used as a fencing field. These values are also spread out over 13 months and nearly 170,000 rows of data since the calculations ignored the missing data fields. We can create new datasets that allow for the removal of the negative values and allow for only positive analysis. We can also address outlier values by determing how to identify them in the dataset and those analyses will proceed below.</p>
</section>
</section>
<section id="first-visuals" class="level3" data-number="1.3.4">
<h3 data-number="1.3.4" class="anchored" data-anchor-id="first-visuals"><span class="header-section-number">1.3.4</span> First Visuals</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="test2_files/figure-html/first_numeric_run-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
[[2]]</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="test2_files/figure-html/first_numeric_run-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
[[3]]</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="test2_files/figure-html/first_numeric_run-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
[[4]]</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="test2_files/figure-html/first_numeric_run-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="test2_files/figure-html/first_numeric_run-5.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
[[2]]</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="test2_files/figure-html/first_numeric_run-6.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
[[3]]</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="test2_files/figure-html/first_numeric_run-7.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
[[4]]</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="test2_files/figure-html/first_numeric_run-8.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>These graphs show the limitations of visualizing these columns. As you can see, the graphs are not very informative. The best information that I can view immediately is the final scatterplot of the time-to-event marked as STEP_1 above and the Agency to whom the call was dispatched. This shows that the greatest spread of data comes for APD calls. This tends to make the most sense since we use auto-dispatch where possible for AFD calls.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="test2_files/figure-html/second_numeric_run-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
[[2]]</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="test2_files/figure-html/second_numeric_run-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
[[3]]</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="test2_files/figure-html/second_numeric_run-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
[[4]]</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="test2_files/figure-html/second_numeric_run-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="test2_files/figure-html/second_numeric_run-5.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
[[2]]</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="test2_files/figure-html/second_numeric_run-6.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
[[3]]</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="test2_files/figure-html/second_numeric_run-7.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
[[4]]</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="test2_files/figure-html/second_numeric_run-8.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="test2_files/figure-html/second_numeric_run-9.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
[[2]]</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="test2_files/figure-html/second_numeric_run-10.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
[[3]]</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="test2_files/figure-html/second_numeric_run-11.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
[[4]]</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="test2_files/figure-html/second_numeric_run-12.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="test2_files/figure-html/second_numeric_run-13.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
[[2]]</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="test2_files/figure-html/second_numeric_run-14.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
[[3]]</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="test2_files/figure-html/second_numeric_run-15.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
[[4]]</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="test2_files/figure-html/second_numeric_run-16.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="test2_files/figure-html/second_numeric_run-17.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
[[2]]</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="test2_files/figure-html/second_numeric_run-18.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
[[3]]</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="test2_files/figure-html/second_numeric_run-19.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
[[4]]</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="test2_files/figure-html/second_numeric_run-20.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="test2_files/figure-html/second_numeric_run-21.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
[[2]]</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="test2_files/figure-html/second_numeric_run-22.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
[[3]]</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="test2_files/figure-html/second_numeric_run-23.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
[[4]]</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="test2_files/figure-html/second_numeric_run-24.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Looking at the visuals for total time elapsed from either the Response_Date or the ClockStartTime, both of which we may discard in future analyses, we do see some very interesting things. Aside from the fact that the histogram and the boxplot aren’t very useful, I have seen something interesting in the scatter plots. Using the ClockStartTime timestamp as a starting point, we can see some calls for service where there is a negative time-to-event value from start to finish. This does not appear when using the Response_Date column. This implies that since re-opening the call starts a new clock, but it doesn’t overwrite a timestamp until the system needs to, that calls may be re-opened, but not formally closed again resulting in a situation where the call appears to end before it begins. Previously, I would have expected this to only happen in something like <ins>The Minority Report</ins> by Phillip K. Dick. It appears that almost all of them can be found where the call source was either not recorded or was generated by the officer.</p>
<p>Next, I think we need to look at outliers, how many of them exist and which columns have the most outlier values. In many cases, we can go back and pull records for the most egregious values to determine what happened. This can also allow us to an acceptable method to remediate those values, if we choose, and then use the remediated values to determine what reported numbers would have been if the outliers were moved back to normalized values.</p>
<p>We can test this with any of the numeric variables. Experiment 1 is</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 52
       ID Reception Problem     Priority Agency Jurisdiction Response_Date      
    &lt;dbl&gt; &lt;chr&gt;     &lt;chr&gt;          &lt;dbl&gt; &lt;chr&gt;  &lt;chr&gt;        &lt;dttm&gt;             
1 2659717 E-911     DOMESTIC V…        1 LAW    Alexandria … 2024-01-01 02:11:07
2 2659739 E-911     ASSAULT NO…        2 LAW    Alexandria … 2024-01-01 02:49:59
3 2659785 E-911     SEIZURE AL…        1 FIRE   200 ALX      2024-01-01 05:10:23
4 2659799 E-911     ASSAULT NO…        3 LAW    Alexandria … 2024-01-01 06:39:14
5 2659800 E-911     DISORDERLY…        2 LAW    Alexandria … 2024-01-01 06:52:47
6 2659812 E-911     911 HANG UP        2 LAW    Alexandria … 2024-01-01 07:42:49
# ℹ 45 more variables: Clock_Start &lt;dttm&gt;, Phone_Start &lt;dttm&gt;,
#   Fixed_Phone_Start &lt;dttm&gt;, First_Keystroke &lt;dttm&gt;, DELTA_RD_CST &lt;dbl&gt;,
#   DELTA_RD_TPU &lt;dbl&gt;, DELTA_RD_FTPU &lt;dbl&gt;, DELTA_RD_FCTK &lt;dbl&gt;,
#   DELTA_CST_TPU &lt;dbl&gt;, DELTA_CST_FTPU &lt;dbl&gt;, DELTA_CST_FCTK &lt;dbl&gt;,
#   DELTA_TPU_FTPU &lt;dbl&gt;, DELTA_TPU_FCTK &lt;dbl&gt;, DELTA_FTPU_FCTK &lt;dbl&gt;,
#   Viewed &lt;dttm&gt;, Queued &lt;dttm&gt;, Fixed_Queued &lt;dttm&gt;, DELTA_QUEUES &lt;dbl&gt;,
#   Phone_End &lt;dttm&gt;, Fixed_Phone_End &lt;dttm&gt;, DELTA_CALLTAKING &lt;dbl&gt;, …</code></pre>
</div>
</div>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>